set(CMAKE_C_COMPILER "clang" CACHE STRING "C compiler" FORCE)
set(CMAKE_CXX_COMPILER "clang++" CACHE STRING "C++ compiler" FORCE)

set(ARCH "arm64" CACHE STRING "Target platform" FORCE)
set(HOD_PLATFORM "macos-arm64")
set(HOD_PLATFORM_DEFINE "PLATFORM_MACOS")
set(HOD_PLATFORM_MACOS True)

set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "Target platform" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET 14 CACHE STRING "OSX Target" FORCE)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wpedantic -Werror")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2 -DNDEBUG")

set(CMAKE_OBJCXX_STANDARD 20)
set(CMAKE_OBJCXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fobjc-arc")

set(CMAKE_POSITION_INDEPENDENT_CODE ON)

message(STATUS "HodEngine -> MacOs Clang Arm64")
