set(CMAKE_C_COMPILER "clang-cl.exe" CACHE STRING "Clang-Cl C compiler" FORCE)
set(CMAKE_CXX_COMPILER "clang-cl.exe" CACHE STRING "Clang-Cl C++ compiler" FORCE)

set(ARCH "x64" CACHE STRING "Target platform" FORCE)
set(HOD_PLATFORM "windows-x64")
set(HOD_PLATFORM_DEFINE "PLATFORM_WINDOWS")
set(HOD_PLATFORM_WINDOWS True)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /DWIN32 /D_WINDOWS /MD /GR /EHsc")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /clang:-Wall /clang:-Wextra /clang:-Wpedantic /clang:-Werror")
set(CMAKE_CXX_FLAGS_DEBUG "/Od /Zi /RTC1")
set(CMAKE_CXX_FLAGS_RELEASE "/O2 /DNDEBUG /Zi")

set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} /DEBUG")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /DEBUG")

add_definitions(-D_CRT_SECURE_NO_WARNINGS)
add_definitions(-D_ITERATOR_DEBUG_LEVEL=0)

message(STATUS "HodEngine -> Windows ClangCl x64")
