set(CMAKE_C_COMPILER "cl.exe" CACHE STRING "MSVC C compiler" FORCE)
set(CMAKE_CXX_COMPILER "cl.exe" CACHE STRING "MSVC C++ compiler" FORCE)

if(CMAKE_GENERATOR MATCHES "Visual Studio")
	set(CMAKE_GENERATOR_PLATFORM "x64" CACHE STRING "Target platform" FORCE)
endif()

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4251 /MD /WX")
set(CMAKE_CXX_FLAGS_DEBUG "/Ob0 /Od /RTC1 /Zi")
set(CMAKE_CXX_FLAGS_RELEASE "/O2 /Ob2 /DNDEBUG /Zi")

set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} /DEBUG")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /DEBUG")

add_definitions(-D_CRT_SECURE_NO_WARNINGS)
add_definitions(-D_ITERATOR_DEBUG_LEVEL=0)

message(STATUS "HodEngine -> Windows MSVC x64")
