if(WIN32)
	set(HOD_PLATFORM_NAME "windows")
	set(HOD_ABI_NAME ${CMAKE_SYSTEM_PROCESSOR})
	set(HOD_PLATFORM_WINDOWS True)
elseif(APPLE)
	if(IOS)
		message(FATAL_ERROR "IOS unsupported")
	elseif(TVOS)
		message(FATAL_ERROR "TVOS unsupported")
	elseif(WATCHOS)
		message(FATAL_ERROR "WATCHOS unsupported")
	elseif(VISIONOS)
		message(FATAL_ERROR "VISIONOS unsupported")
	else() # MacOs
		set(HOD_PLATFORM_NAME "macos")
		set(HOD_ABI_NAME ${CMAKE_SYSTEM_PROCESSOR})
		set(HOD_PLATFORM_MACOS True)
	endif()
elseif(LINUX)
	set(HOD_PLATFORM_NAME "linux")
	set(HOD_ABI_NAME ${CMAKE_SYSTEM_PROCESSOR})
	set(HOD_PLATFORM_LINUX True)
elseif(ANDROID)
	set(HOD_PLATFORM_NAME "android")
	set(HOD_ABI_NAME ${ANDROID_ABI})
	set(HOD_PLATFORM_ANDROID True)
endif()

string(TOUPPER ${HOD_PLATFORM_NAME} HOD_PLATFORM_NAME_UPPER)
set(HOD_PLATFORM_DEFINE_TYPE "PLATFORM_${HOD_PLATFORM_NAME_UPPER}")
set(HOD_PLATFORM_DEFINE_VALUE "HOD_PLATFORM=${HOD_PLATFORM_NAME}")
set(HOD_ABI_DEFINE_VALUE "HOD_ABI=${HOD_ABI_NAME}")

set(HOD_PLATFORM_DEFINE)
list(APPEND HOD_PLATFORM_DEFINE
	${HOD_PLATFORM_DEFINE_TYPE}
	${HOD_PLATFORM_DEFINE_VALUE}
	${HOD_ABI_DEFINE_VALUE}
)

message(STATUS "Platform: ${HOD_PLATFORM_NAME}")
message(STATUS "Abi: ${HOD_ABI_NAME}")